name: dart_backend_client
description: A dart package to provide a rest interface
version: 0.14.0
homepage: https://www.jayjah.de
repository: https://github.com/jayjah/dart_backend_client

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  intl: ^0.18.0
  hive: ^2.2.3
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  retrofit: ^4.7.0
  logger: ^2.6.1
  pretty_dio_logger: ^1.4.0
  http: ^1.4.0
  osm_nominatim: ^4.0.1
  #dio_logger: any
dev_dependencies:
  test: any
  retrofit_generator: any
  build_runner: any
  hive_generator: any