name: dart_backend_client
description: A dart package to provide a rest interface
version: 0.10.0
homepage: https://www.jayjah.de
repository: https://github.com/jayjah/dart_backend_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.3
  intl: ^0.18.0
  hive: ^2.2.3
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  http: ^0.13.5
  osm_nominatim: ^2.0.1
  #dio_logger: any
dev_dependencies:
  test: any
  retrofit_generator: any
  build_runner: any
  hive_generator: any
  lints: ^1.0.1