name: dart_backend_client
description: A dart package to provide a rest interface
version: 0.0.2
author: jayjah <jah@jayjah.de>
homepage: https://www.jayjah.de
repository: https://github.com/jayjah/dart_backend_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: any
  intl: any
  hive: any
  json_serializable: any
  json_annotation: any
  retrofit: any
  logger: any
  pretty_dio_logger: any
dev_dependencies:
  test: any
  retrofit_generator: any
  build_runner: any
  hive_generator: any