name: dart_backend_client
description: A flutter package to provide a rest interface to dart_backend
version: 0.0.1
author: Markus Krebs <jah@jayjah.de>
homepage: https://www.jayjah.de
repository: https://github.com/jayjah/dart_backend_client

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: any
  path_provider: any
  intl: any
  hive: any
  package_info_plus: any
  json_serializable: any
  json_annotation: any
  retrofit: any
  logger: any
dev_dependencies:
  flutter_test:

    sdk: flutter
  retrofit_generator: any
  build_runner: any
  hive_generator: any
flutter: