name: dart_backend_client
description: A dart package to provide a rest interface
version: 0.0.2
author: jayjah <jah@jayjah.de>
homepage: https://www.jayjah.de
repository: https://github.com/jayjah/dart_backend_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: 3.0.10
  intl: 0.16.1
  hive: 1.4.4+1
  json_serializable: 3.5.1
  json_annotation: 3.1.1
  retrofit: 1.3.4+1
  logger: 0.9.4
  pretty_dio_logger: 1.1.1
dev_dependencies:
  test: any
  retrofit_generator: any
  build_runner: any
  hive_generator: any