name: dart_backend_client
description: A dart package to provide a rest interface
version: 0.3.1
homepage: https://www.jayjah.de
repository: https://github.com/jayjah/dart_backend_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.3
  intl: 0.17.0
  hive: 2.0.4
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  retrofit: ^3.0.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  http: ^0.13.4
  osm_nominatim: ^2.0.1
  #dio_logger: any
dev_dependencies:
  test: any
  retrofit_generator: any
  build_runner: any
  hive_generator: any